### ISSUE TITLE
Repack .cat files

### ISSUE THREAD

**Issue by imjinjia** [rewjx/GameEngineTools#1]
大佬，可以更新下工具加入打包功能吗？

**Comment by rewjx** [comment]
> 大佬，可以更新下工具加入打包功能吗？

指的是 Touhou Genso Wanderer里的.cat文件吗？不过抱歉，最近几个月真的很忙，可能没啥时间（如果有时想写的话可能就加进去了，但是整体上没计划、没时间支持打包）。
而且我逆向能力不足，有的字段不知道啥含义，解包没问题，但是封包的话即使实现了，可能也只打算支持封原包里有的文件（文件内容可以替换，但是只封这些文件名的文件，新增文件啥的就不支持了，毕竟新增文件了不改脚本啥的，游戏也没法读，封进去也没用。）

**Comment by rewjx** [comment]
> 大佬，可以更新下工具加入打包功能吗？

刚刚更新了一下，支持"AQUA"文件头的封包文件打包替换。
我看了 Touhou Genso Wanderer -Lotus Labyrinth R-的.cat文件都是"AQUA"文件头，有部分其他文件是”ASFA"文件头，这个暂时不考虑了，之前逆的时候有更多字段没搞明白。

**Comment by imjinjia** [comment]
@rewjx 非常感谢大佬，我只是在做汉化，新增文件没意义。苦于没有写程序能力，斗胆向大佬再提个请求，就是解包出来的文本，结构很简单，希望能写个简单小程序来导出导入。

如果可以，加个联系方式啥的，我们这里有人应该会发个大红包感谢一下。
[text.zip](https://github.com/rewjx/GameEngineTools/files/8201860/text.zip)
