### ISSUE TITLE
Unpacking movies.mov failed

### ISSUE THREAD

**Issue by imjinjia** [rewjx/GameEngineTools#2]
大佬，我又来了。
刚发现不能解包movies.mov，文件太大不好上传，大佬那边应该有这个文件吧，没有的话我再上传。
游戏视频应该内嵌字幕，完整汉化就要对视频动手。

**Comment by imjinjia** [comment]
还有这两个
[samples.zip](https://github.com/rewjx/GameEngineTools/files/8202062/samples.zip)

**Comment by rewjx** [comment]
> 大佬，我又来了。 刚发现不能解包movies.mov，文件太大不好上传，大佬那边应该有这个文件吧，没有的话我再上传。 游戏视频应该内嵌字幕，完整汉化就要对视频动手。

不可思议的幻想乡莲花迷宫R不是有官方汉化吗，还需要自己汉化？ 或者你是用来解包哪个游戏的，我是争对steam版莲花迷宫R测试的，视频mov也能解包，解包后的文件用视频播放器能直接播放。如果不是这个游戏，需要你提供下游戏名。（如果是主机端，没有pc端就算了，不会主机游戏的分析）

另外text.bin的修改其实可能很麻烦。里面有些字节不知道啥含义，而且很可能其他地方会有文本的偏移或长度信息，一旦修改了字符串，这些信息都得修改，这不只是修改text.bin的问题。总之难度可能很大，而且我水平也很菜，可能做不了这个。

更关键的是我最近几个月真的很忙， 不然还是可以研究一下text.bin的修改的。但是这一研究估计就得花上一整周的时间。

**Comment by imjinjia** [comment]
@rewjx 是psv版的，我又试了其他文件，部分文件同样无法解包，我上传的那两个大佬可以试试。

**Comment by rewjx** [comment]
> @rewjx 是psv版的，我又试了其他文件，部分文件同样无法解包，我上传的那两个大佬可以试试。

psv版的莲花迷宫吗。我没有主机游戏的分析经验，那可能帮不了什么忙了。（你能找到psv端的程序文件吗，类似pc端的exe，如果能上传一份程序文件，我有时间可以静态分析看看，不然只能靠猜。）

**Comment by imjinjia** [comment]
@rewjx psv上的是eboot跟pc上的区别很大的
[eboot.zip](https://github.com/rewjx/GameEngineTools/files/8202284/eboot.zip)
。
大部分文件可以解包，说明遗漏了某些细节。大佬加油。

**Comment by rewjx** [comment]
> @rewjx psv上的是eboot跟pc上的区别很大的 [eboot.zip](https://github.com/rewjx/GameEngineTools/files/8202284/eboot.zip) 。 大部分文件可以解包，说明遗漏了某些细节。大佬加油。

你可以自己编译程序吗，如果能我就不发布release了。

**Comment by imjinjia** [comment]
@rewjx 那么快就更新了？没编译过这种，劳烦你了。

**Comment by rewjx** [comment]
> @rewjx 那么快就更新了？没编译过这种，劳烦你了。

因为后面还可能改，所以不想频繁release，只要有visual studio就行，很简单的。把代码下载下来，用vs打开，然后编译就行了，没有复杂的依赖啥的。

**Comment by imjinjia** [comment]
@rewjx 没问题，感谢。
如果能加个联系方式就太好了。

**Comment by rewjx** [comment]
> @rewjx 没问题，感谢。 如果能加个联系方式就太好了。

你给个q号，我加你吧。

**Comment by imjinjia** [comment]
@rewjx 
1558830841
验证答案就是rewjx
