### ISSUE TITLE
Cstx script import problem

### ISSUE THREAD

**Issue by 124asd** [rewjx/GameEngineTools#3]
大佬你好 我编译了你的CatSystem tool后去用来导出cstx文件里面的文本 但是在测试导入的时候出现了问题 游戏不能运行文本 试用日文原文本导入新cstx文件也会出现一样的问题 不知道我是不是弄错了步骤还是其他

**Comment by rewjx** [comment]
啥游戏，我是针对悠久のカンパネラ这写的，没见过其他用cstx的游戏。
如果就是悠久のカンパネラ这游戏，那可能是你使用不对，或者改错了内容，除了我之外还有其他人用过这个工具改悠久のカンパネラ这游戏，应该不存在大bug。

**Comment by 124asd** [comment]
> 啥游戏，我是针对悠久のカンパネラ这写的，没见过其他用cstx的游戏。 如果就是悠久のカンパネラ这游戏，那可能是你使用不对，或者改错了内容，除了我之外还有其他人用过这个工具改悠久のカンパネラ这游戏，应该不存在大bug。

是另一个游戏 名叫一途な（処女→）彼女と恋したい 这个游戏也是用catsystem unity的 然后文本可以导出来 但导入是不能成功 换原日文文本也是一样问题 谢谢大佬回复

**Comment by rewjx** [comment]
> 

我抽空看看这游戏。

**Comment by 124asd** [comment]
> > 
> 
> 我抽空看看这游戏。

好的 谢谢大佬

**Comment by rewjx** [comment]
> > > 
> > 
> > 
> > 我抽空看看这游戏。
> 
> 好的 谢谢大佬

经过测试，你导入文本时不要用-no这个选项，不用-no, 我至少修改了文本没问题。 

之前那个游戏用-no也没问题，但是自己要特别小心，因为有的\t是有特殊作用的，不能随便删除。其实默认情况最好不要用-no选项，除非自己特别有把握，就是要那样改（然而一般也没必要这样做）。但这个游戏不知道为什么啥都不改，用-no也不行，估计有点bug，不想仔细看了，不用-no选项就可以了。

当然如果要汉化啥的，还得处理字体，默认的字体是不包含绝大部分中文字的，这个就不在我这工具范围之内了，需要自己用unity弄。

**Comment by 124asd** [comment]
> 

好的 谢谢  \t我那边是会筛选掉的 非常感谢大佬的帮助

**Comment by rewjx** [comment]
> > 
> 
> 好的 谢谢 \t我那边是会筛选掉的 非常感谢大佬的帮助

不加-no选项，就不需要注意空格，\t之类的。 -omsg选项似乎需要注意换行（其实尽量保持原游戏那样就好了），-pmsg选项似乎换行也不需要注意了（记不大清了），但记得好像有点问题，好像选项的地方会提取到部分代码来着，但只要不改到了它，应该不影响程序运行。
而且根据悠久のカンパネラ这个游戏来看，出问题的还是比较少。对于有问题的，如果有能力也可以自己用 all方式导出，然后自己找规律，用正则啥的提取文本，然后翻译，再用all方式导入就可以了。

冒昧的问一下是要汉化这作吗？

**Comment by 124asd** [comment]
> > > 
> > 
> > 
> > 好的 谢谢 \t我那边是会筛选掉的 非常感谢大佬的帮助
> 
> 不加-no选项，就不需要注意空格，\t之类的。 -omsg选项似乎需要注意换行（其实尽量保持原游戏那样就好了），-pmsg选项似乎换行也不需要注意了（记不大清了），但记得好像有点问题，好像选项的地方会提取到部分代码来着，但只要不改到了它，应该不影响程序运行。
> 
> 冒昧的问一下是要汉化这作吗？

是的 非常抱歉再打扰你了 去掉-no也会出现问题 进入游戏是这样的 文本仍然不弹出
![问题](https://user-images.githubusercontent.com/67571290/181280761-bc3b233b-77a9-4267-9add-4c1b4ca7a5d8.png)

**Comment by 124asd** [comment]
> 

用十六进制编辑器看了下两者编码的对比 可能是问题所在
![可能原因](https://user-images.githubusercontent.com/67571290/181281822-16b6c8df-2a68-42ac-8b37-fc695ec630c2.png)

**Comment by rewjx** [comment]
> > > > 
> > > 
> > > 
> > > 好的 谢谢 \t我那边是会筛选掉的 非常感谢大佬的帮助
> > 
> > 
> > 不加-no选项，就不需要注意空格，\t之类的。 -omsg选项似乎需要注意换行（其实尽量保持原游戏那样就好了），-pmsg选项似乎换行也不需要注意了（记不大清了），但记得好像有点问题，好像选项的地方会提取到部分代码来着，但只要不改到了它，应该不影响程序运行。
> > 冒昧的问一下是要汉化这作吗？
> 
> 是的 非常抱歉再打扰你了 去掉-no也会出现问题 进入游戏是这样的 文本仍然不弹出 ![问题](https://user-images.githubusercontent.com/67571290/181280761-bc3b233b-77a9-4267-9add-4c1b4ca7a5d8.png)

我这里没问题啊，我想起来了，导出和导入要匹配。要加-no,自己导出时就要加-no，然后注意不加空格，tab。然后导入时才可以加-no. 

你用的啥命令，啥方式导出的，我是用的
导出：
cstxpack.exe -e -op <cstx文件所在目录> -sp <保存目录> -text omsg -cp 65001 -com true
导入：
cstxpack.exe -i -op <原始未修改的cstx文件所在目录> -sp <保存目录> -ip <翻译或修改后的txt文本目录> -text omsg -cp 65001 -com true
你这是修改过文本吗，还是完全没改过。如果改过，那几个字节不一样是正常的。
如果没改过，我这里是加了-no才是这样的，不加就是一模一样的。

**Comment by 124asd** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 好的 谢谢 \t我那边是会筛选掉的 非常感谢大佬的帮助
> > > 
> > > 
> > > 不加-no选项，就不需要注意空格，\t之类的。 -omsg选项似乎需要注意换行（其实尽量保持原游戏那样就好了），-pmsg选项似乎换行也不需要注意了（记不大清了），但记得好像有点问题，好像选项的地方会提取到部分代码来着，但只要不改到了它，应该不影响程序运行。
> > > 冒昧的问一下是要汉化这作吗？
> > 
> > 
> > 是的 非常抱歉再打扰你了 去掉-no也会出现问题 进入游戏是这样的 文本仍然不弹出 ![问题](https://user-images.githubusercontent.com/67571290/181280761-bc3b233b-77a9-4267-9add-4c1b4ca7a5d8.png)
> 
> 我这里没问题啊，我想起来了，导出和导入要匹配。要加-no,自己导出时就要加-no，然后注意不加空格，tab。然后导入时才可以加-no.
> 
> 你用的啥命令，啥方式导出的，我是用的 导出： cstxpack.exe -e -op <cstx文件所在目录> -sp <保存目录> -text omsg -cp 65001 -com true 导入： cstxpack.exe -i -op <原始未修改的cstx文件所在目录> -sp <保存目录> -ip <翻译或修改后的txt文本目录> -text omsg -cp 65001 -com true 你这是修改过文本吗，还是完全没改过。如果改过，那几个字节不一样是正常的。 如果没改过，我这里是加了-no才是这样的，不加就是一模一样的。

刚刚发现我用的导出命令是照着usgae写的 所以是CstxPack.exe -e -op <cstx文件所在目录> -sp <保存目录> -text all -com true -cp 65001
CstxPack.exe -i -op <原始未修改的cstx文件所在目录> -sp <保存目录> -ip <翻译或修改后的txt文本目录> -text omsg -com true -cp 65001
非常抱歉打扰你了（羞愧）

**Comment by 124asd** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 好的 谢谢 \t我那边是会筛选掉的 非常感谢大佬的帮助
> > > > 
> > > > 
> > > > 不加-no选项，就不需要注意空格，\t之类的。 -omsg选项似乎需要注意换行（其实尽量保持原游戏那样就好了），-pmsg选项似乎换行也不需要注意了（记不大清了），但记得好像有点问题，好像选项的地方会提取到部分代码来着，但只要不改到了它，应该不影响程序运行。
> > > > 冒昧的问一下是要汉化这作吗？
> > > 
> > > 
> > > 是的 非常抱歉再打扰你了 去掉-no也会出现问题 进入游戏是这样的 文本仍然不弹出 ![问题](https://user-images.githubusercontent.com/67571290/181280761-bc3b233b-77a9-4267-9add-4c1b4ca7a5d8.png)
> > 
> > 
> > 我这里没问题啊，我想起来了，导出和导入要匹配。要加-no,自己导出时就要加-no，然后注意不加空格，tab。然后导入时才可以加-no.
> > 你用的啥命令，啥方式导出的，我是用的 导出： cstxpack.exe -e -op <cstx文件所在目录> -sp <保存目录> -text omsg -cp 65001 -com true 导入： cstxpack.exe -i -op <原始未修改的cstx文件所在目录> -sp <保存目录> -ip <翻译或修改后的txt文本目录> -text omsg -cp 65001 -com true 你这是修改过文本吗，还是完全没改过。如果改过，那几个字节不一样是正常的。 如果没改过，我这里是加了-no才是这样的，不加就是一模一样的。
> 
> 刚刚发现我用的导出命令是照着usgae写的 所以是CstxPack.exe -e -op <cstx文件所在目录> -sp <保存目录> -text all -com true -cp 65001 CstxPack.exe -i -op <原始未修改的cstx文件所在目录> -sp <保存目录> -ip <翻译或修改后的txt文本目录> -text omsg -com true -cp 65001 非常抱歉打扰你了（羞愧）

之前是按这个example里面的命令写的
![usage](https://user-images.githubusercontent.com/67571290/181284506-34827d8a-a772-4662-a3f3-66f5c4b680cc.png)

**Comment by rewjx** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 好的 谢谢 \t我那边是会筛选掉的 非常感谢大佬的帮助
> > > > 
> > > > 
> > > > 不加-no选项，就不需要注意空格，\t之类的。 -omsg选项似乎需要注意换行（其实尽量保持原游戏那样就好了），-pmsg选项似乎换行也不需要注意了（记不大清了），但记得好像有点问题，好像选项的地方会提取到部分代码来着，但只要不改到了它，应该不影响程序运行。
> > > > 冒昧的问一下是要汉化这作吗？
> > > 
> > > 
> > > 是的 非常抱歉再打扰你了 去掉-no也会出现问题 进入游戏是这样的 文本仍然不弹出 ![问题](https://user-images.githubusercontent.com/67571290/181280761-bc3b233b-77a9-4267-9add-4c1b4ca7a5d8.png)
> > 
> > 
> > 我这里没问题啊，我想起来了，导出和导入要匹配。要加-no,自己导出时就要加-no，然后注意不加空格，tab。然后导入时才可以加-no.
> > 你用的啥命令，啥方式导出的，我是用的 导出： cstxpack.exe -e -op <cstx文件所在目录> -sp <保存目录> -text omsg -cp 65001 -com true 导入： cstxpack.exe -i -op <原始未修改的cstx文件所在目录> -sp <保存目录> -ip <翻译或修改后的txt文本目录> -text omsg -cp 65001 -com true 你这是修改过文本吗，还是完全没改过。如果改过，那几个字节不一样是正常的。 如果没改过，我这里是加了-no才是这样的，不加就是一模一样的。
> 
> 刚刚发现我用的导出命令是照着usgae写的 所以是CstxPack.exe -e -op <cstx文件所在目录> -sp <保存目录> -text all -com true -cp 65001 CstxPack.exe -i -op <原始未修改的cstx文件所在目录> -sp <保存目录> -ip <翻译或修改后的txt文本目录> -text omsg -com true -cp 65001 非常抱歉打扰你了（羞愧）

呃，导出和导入必须匹配才行。不同方式导出的文本都不一样，不匹配肯定会出问题。-text 的选项有3个:all, omsg, pmsg，导出时用的啥导入时就必须用啥。 另外-no也得匹配，但最好不用。

可能我写的usage有点误导，主要是想多展示几个参数，就没配对。但-text那里有说明This parameter(-text) needs to be the same when importing and exporting!!!

**Comment by 124asd** [comment]
> 

嗯 是我莽了 没仔细看说明 直接照example写了 非常谢谢大佬的帮助（点赞）

**Comment by 124asd** [comment]
> > 
> 
> 嗯 是我莽了 没仔细看说明 直接照example写了 非常谢谢大佬的帮助（点赞）

后面可能会咨询大佬一些程序问题 可以加个qq1248349736吗 （点赞）
