### ISSUE TITLE
System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

### ISSUE THREAD

**Issue by gembleman** [rewjx/GameEngineTools#4]
C:\CstxPack.exe -u -op "C:\test_script.cstx" -sp "C:\ddd"

처리되지 않은 예외: System.IO.IOException: 디렉터리 이름이 올바르지 않습니다.

   위치: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   위치: System.IO.FileSystemEnumerableIterator`1.CommonInit()
   위치: System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   위치: System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   위치: CstxPack.CSTXScript.ProcessMain(OpType op, TextType textType)
   위치: CstxPack.Program.Process(CmdParser parser)
   위치: CstxPack.Program.Main(String[] args)

Why this happening?

**Comment by rewjx** [comment]
The "-op" parameter needs a directory, not a full path. Even if you only need to process one file, you can put it in a directory and give the directory path. And you need to make sure you have enough windows privilege.

**Comment by gembleman** [comment]
Thank you for your kindness.
Thanks to you, I was able to solve the difficult problem of game extraction.
